[[mgr.prepend_keymap]]
on   = [ "g", "s" ]
run  = "cd /mnt/DATA/"
desc = "Go to DATA"

[[mgr.prepend_keymap]]
on   = [ "W" ]
run  = 'shell "~/dots/scripts/wallpaper.zsh \"$1\"" --orphan'
desc = "Set as Wallpaper (Wallust + Awww)"
