[[mgr.prepend_keymap]]
on   = [ "g", "s" ]
run  = "cd /mnt/DATA/"
desc = "Go to DATA"

[[mgr.prepend_keymap]]
on   = [ "W" ]
run  = 'shell "~/dots/scripts/wallpaper.zsh \"$1\"" --orphan'
desc = "Set as Wallpaper (Wallust + Awww)"

[[mgr.prepend_keymap]]
on   = [ "g", "t" ]
run  = "cd ~/.local/share/Trash/files"
desc = "Go to Trash Directory"

[[mgr.prepend_keymap]]
on   = [ "g", "T" ]
run  = "shell 'kitty --class restore_float -e trash-restore' --block"
desc = "Restore from trash"

[[mgr.prepend_keymap]]
on   = [ "g", "m" ]
run  = "cd /mnt/DATA/Music/"
desc = "Go to Music"
