# ==========================================
# 1. CORE ALGORITHMS
# ==========================================

backend = "fast-resize" #Optiions: full, resized, wal, thumb, fast-resize, fastresize, kmeans

color_space = "lab" #Optiions: lab, lab-mixed, labmixed, lch, lch-mixed, lchmixed, lch-ansi, lchansi 

palette = "dark" #Optiions: dark, dark16, dark-comp, darkcomp, dark-comp16, darkcomp16, ansi-dark, ansidark, ansi-dark16, ansidark16, hard-dark, harddark, hard-dark16, harddark16, hard-dark-comp, harddarkcomp, hard-dark-comp16, harddarkcomp16, light, light16, light-comp, lightcomp, light-comp1, lightcomp1, soft-dark, softdar, soft-dark16, softdark16, soft-dark-comp, softdarkcomp, soft-dark-comp16, softdarkcomp16, soft-light, softlight, soft-light16, softlight16, soft-light-comp, softlightcomp, soft-light-comp16, softlightcomp16
    

# ==========================================
# 2. VIBRANCY CONTROLS
# ==========================================

# Boost saturation to fight "dullness". 
# Default is usually lower. 60-70 makes colors pop.
#saturation = 60

# Threshold determines how different colors must be to be picked.
# 30 prevents wallust from picking 3 slightly different shades of grey/blue.

# ==========================================
# 3. TEMPLATES
# ==========================================

[templates]

# Cava
cava = { template = 'cava.conf', target = '~/dots/cava/themes/adaptive' }

# Hyprland
hypr = { template = 'colors.conf', target = '~/dots/hypr/colors.conf' }

# Kitty
kitty = { template = 'kitty', target = '~/.cache/wallust/colors-kitty.conf' }

# Waybar 
waybar = { template = 'waybar', target = '~/dots/waybar/colors.css' }

# Zathura
zathura = { template = 'zathura', target = '~/dots/zathura/zathurarc'}

# rmpc 

rmpc = { template = 'rmpc', target = '~/.config/rmpc/themes/adaptive.ron'}
